### ISSUE TITLE
Need Help to Get Started

### ISSUE THREAD

**Issue by aress31** [blikblum/nextbone-routing#17]
Hi @blikblum,

First of all, very nice initiative to implement a web component/application centered routing library! That is exactly what I was looking for!

I am trying to get the routing working and did the following steps:
1. Created a `router.js` file containing:
```js
import { Router } from 'nextbone-routing';
import './views/shop-hello-world.js';

// callback function that defines the route tree
// can be defined also as an array
const routes = function (route) {
  route('application', { path: '/' }, () => {
    route('home', { component: 'shop-hello-world', path: '' });
  });
};

const router = new Router({
  log: true,
  logError: true,
  // element where the root routes will be rendered
  outlet: '#outlet',
  routes,
});

//start listening to URL changes
router.listen();
```

2. Referencing the above file - `router.js` - in my shop-app.js component:
```js
--- SNIP ---
import { css, html, LitElement } from 'lit-element';
import '../router.js';

class ShopApp extends LitElement {
  --- SNIP ---

  render() {
    return html`
      <mwc-drawer hasHeader type="modal">
        <!-- <my-drawer></my-drawer> -->
        <div slot="appContent">
          <mwc-top-app-bar
            centerTitle
            @MDCTopAppBarFixed:nav=${() =>
              (this.drawer.open = !this.drawer.open)}
          >
            --- SNIP ---
            </div>
            <main id="outlet">
            </main>
          </mwc-top-app-bar>
        </div>
      </mwc-drawer>
    `;
  }
}

customElements.define('shop-app', ShopApp);
```

- The `shop-hello-world.js` file contains:
```js
import { html, LitElement } from 'lit-element';

class ShopHelloWorld extends LitElement {
  render() {
    return html`<h1>Hello World!</h1>`;
  }
}

customElements.define('shop-hello-world', ShopHelloWorld);
```

I have got couple of questions:
1. Please could you help with the above code, I do not understand why it does not work.
2. Do I need to use `import '../router.js';` in all my views where client side routing is performed or importing it in the app-shell is enough?
3. How could I change the following code to lazy load my view components?
```js
const routes = function (route) {
  route('application', { path: '/' }, () => {
    route('home', { component: 'shop-hello-world', path: '' });
  });
};
```

EDIT: I hope the following can help:
![image](https://user-images.githubusercontent.com/11601622/89711652-74b23280-d983-11ea-9218-f0cc974e20d6.png)

EDIT1: Maybe it is worth mentioning that `shadowDom` is `on`.

Yes! it seems that disabling `shadowDom` makes the routing work. How about adding an option to the router to define if `shadowDom` is `on` of `off`?

```js
  createRenderRoot() {
    return this;
  }
```

EDIT2: Also for some weird reasons, it seems that I am unable to configure more than 1 route:
```js
import { Router } from 'nextbone-routing';
import './views/shop-hello-world-alt.js';
import './views/shop-hello-world.js';

// callback function that defines the route tree
// can be defined also as an array
const routes = function (route) {
  route('application', { path: '/' }, () => {
    route('login', { component: 'shop-hello-world-alt', path: '' });
    route('home', { component: 'shop-hello-world', path: '' });
  });
};

const router = new Router({
  log: true,
  logError: true,
  // element where the root routes will be rendered
  outlet: '#outlet',
  routes,
});

//start listening to URL changes
router.listen();
```

![image](https://user-images.githubusercontent.com/11601622/89712069-5dc10f80-d986-11ea-81c2-692bbd23f9b8.png)

Looking forward to your help,
Alex

**Comment by blikblum** [comment]
> First of all, very nice initiative to implement a web component/application centered routing library! That is exactly what I was looking for!

Hi.

First you can also consider [slick-router](https://github.com/blikblum/slick-router) with [wc middleware](https://github.com/blikblum/slick-router/blob/master/docs/middlewares/wc.md)  that is a web component routing library, smaller and more focused which nextbone-routing extends. Example [here](https://github.com/blikblum/lit-element-mobx-realworld-example-app) 

nextbone-routing is centered around the stateful Route class a powerful concept but kind of opinionated (its the library i use most but i'd like to make you aware ). Route instances allow to decouple routing from the component and many powerful things like [this](https://github.com/blikblum/nextbone-wires/blob/master/src/books/route.js)

> Please could you help with the above code, I do not understand why it does not work.
> Yes! it seems that disabling shadowDom makes the routing work. How about adding an option to the router to define if shadowDom is on of off?

When outlet is a string it uses [document.querySelector](https://github.com/blikblum/nextbone-routing/blob/master/src/router.js#L98) which does not works with shadowDom. You can pass an HTMLElement instance or a function returning an Region class as outlet option. This should work with shadow dom

> Do I need to use import '../router.js'; in all my views where client side routing is performed or importing it in the app-shell is enough?

No. Just use at start of app

The router instance is accessible through $router property in a Route instance

> How could I change the following code to lazy load my view components?

Lazy loading is done at Route class level. slick-router does at component level

Pass a function to class option:

ShopRoute.js
```js
import './shop-hello.js'

export default ShopRoute {
  static component = 'shop-hello-world'
}
```

```js
function AsyncShopRoute () {
  return import('../ShopRoute.js');
}

const routes = function (route) {
  route('application', { path: '/' }, () => {
    route('home', { class: AsyncShopRoute , path: '' });
  });
};
```

**Comment by blikblum** [comment]
> EDIT2: Also for some weird reasons, it seems that I am unable to configure more than 1 route:

Each sibling route must have an unique path. If you omit the path option it will use name as path

**Comment by aress31** [comment]
@blikblum thank you very much for taking the time to address all my points!

**Comment by blikblum** [comment]
FYI i just did a new release allowing to lazy load at component level and improved a bit the documentation
